# -*- coding: utf-8 -*-
"""capstone_dico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jf9g5UL6lBqQDcov_ym6LPln0ckDzMM2

## Model Train
"""

!pip install face_recognition

from imutils import paths
import face_recognition
import pickle
import cv2
import os

# daftar gambar di folder dataset
print("[INFO] Memulai proses...")
imagePaths = list(paths.list_images("dataset"))

# Mengenali nama pengguna
yLabel = []
xTrain = []

# pengulangan pencarian gambar + extract nama berdasarkan dataset gambar
for (i, imagePath) in enumerate(imagePaths):
	print("[INFO] memproses gambar {}/{}".format(i + 1,
		len(imagePaths)))
	name = imagePath.split(os.path.sep)[-2]

# memuat gambar input dan mengonversinya dari RGB (ke OpenCV)
	image = cv2.imread(imagePath)
	rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# mendeteksi (x, y)-koordinat kotak pembatas sesuai dengan setiap wajah di gambar input
	boxes = face_recognition.face_locations(rgb,model="hog")

# menghitung keakuratan gambar untuk wajah pengguna
	encodings = face_recognition.face_encodings(rgb, boxes)

# perulangan encodings
	for encoding in encodings:
		yLabel.append(encoding)
		xTrain.append(name)

# menghapus encoding wajah dan nama di disk
print("[INFO] serializing encodings...")
data = {"encodings": yLabel, "names": xTrain}
f = open("encodings.pickle", "wb")
f.write(pickle.dumps(data))
f.close()

"""### contoh

"""